"""Constants for the Ksenia Lares Alarm integration."""

DOMAIN = "ksenia_lares"
MANUFACTURER = "KSENIA"
DEFAULT_TIMEOUT = 15

DATA_ZONES = "ZONES"
DATA_PARTITIONS = "PARTITIONS"
DATA_TEMPERATURES = "TEMPERATURES"
DATA_OUTPUTS = "OUTPUTS"

ZONE_STATUS_ALARM = "ALARM"
ZONE_STATUS_NORMAL = "NORMAL"
ZONE_STATUS_NOT_USED = "NOT_USED"

ZONE_BYPASS_OFF = "UN_BYPASS"
ZONE_BYPASS_ON = "BYPASS"

OUTPUT_STATUS_OFF = "OFF"
OUTPUT_STATUS_ON = "ON"

PARTITION_STATUS_DISARMED = "DISARMED"
PARTITION_STATUS_ARMED = "ARMED"
PARTITION_STATUS_ARMED_IMMEDIATE = "ARMED_IMMEDIATE"
PARTITION_STATUS_ARMING = "EXIT"
PARTITION_STATUS_PENDING = "PREALARM"
PARTITION_STATUS_ALARM = "ALARM"

CONF_PIN = "pin"
CONF_SCAN_INTERVAL = "scan_interval"

CONF_PARTITION_AWAY = "partition_away"
CONF_PARTITION_HOME = "partition_home"
CONF_PARTITION_NIGHT = "partition_night"

CONF_SCENARIO_AWAY = "scenario_away"
CONF_SCENARIO_HOME = "scenario_home"
CONF_SCENARIO_NIGHT = "scenario_night"
CONF_SCENARIO_DISARM = "scenario_disarm"

DATA_COORDINATOR = "coordinator"
DATA_UPDATE_LISTENER = "update_listener"
